name: Push

on:
  - push

jobs:
  build-deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Tag release
        run: |
          git tag "$(date +'%Y-%m-%d_%H-%M-%S')"
          git push --tags
      - name: Release
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          artifacts: "main.pdf"
